name: Hello World
on:
  push:
    branches:
    - main
    
  jobs:
  build:
      first-hello-world-job:
      runs-on: ubuntu latest
      steps:
       - name: checkout code
       uses: actions/checkout@v3
       
       - name: Print message
       run: echo "Hello world GA Testing"
    run-pytest:
    steps:
     - name: checkout code
       uses: actions/checkout@v3
     - name: setup Python
      uses: actions/setup-python@v3
      with:
        Python -m pip install --upgarde pip
        pip install pytest
     - name: Run testcases
       run: pytest
